auto: true
server: true
permalink: none
baseurl: http://blog.fabian-blechschmidt.de/
name: Blog - Magento, Security, Testing - Fabian Blechschmidt
description: Notepad and information pool about Magento, Security, Testing
url: http://blog.fabian-blechschmidt.de/
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: Fabian_ikono
      author: Fabian Blechschmidt
      categories:
      - articles